name = "taxonomyapp"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[pages.env_vars]]
NEXT_PUBLIC_CONTENTFUL_SPACE_ID = ""
NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN = ""
NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN = ""
CONTENTFUL_PREVIEW_SECRET = "" 